
# Generated by CodiumAI

class TestCreateSubXml:

    #  Correctly writes XML files when buffer is not empty
    def test_writes_xml_when_buffer_not_empty(self):
        import os
        import xml.etree.ElementTree as ET
        from tempfile import TemporaryDirectory

        def create_sub_xml(name, buffer, case_count, dir_path):
            if buffer:
                root = ET.Element('testcase')
                for line in buffer:
                    root.append(line)
                tree = ET.ElementTree(root)
                tree.write(os.path.join(dir_path, f"{name}_{case_count}.xml"))

        with TemporaryDirectory() as temp_dir:
            buffer = [ET.Element('row', attrib={'id': '1'})]
            create_sub_xml('test_case', buffer, 1, temp_dir)
            expected_file = os.path.join(temp_dir, 'test_case_1.xml')
            assert os.path.exists(expected_file)

            tree = ET.parse(expected_file)
            root = tree.getroot()
            assert root.tag == 'testcase'
            assert len(root) == 1
            assert root[0].tag == 'row'
            assert root[0].attrib['id'] == '1'

    #  Handles empty buffer without attempting to write an XML file
    def test_does_not_write_xml_when_buffer_empty(self):
        import os
        from tempfile import TemporaryDirectory

        def create_sub_xml(name, buffer, case_count, dir_path):
            if buffer:
                root = ET.Element('testcase')
                for line in buffer:
                    root.append(line)
                tree = ET.ElementTree(root)
                tree.write(os.path.join(dir_path, f"{name}_{case_count}.xml"))

        with TemporaryDirectory() as temp_dir:
            buffer = []
            create_sub_xml('test_case', buffer, 1, temp_dir)
            expected_file = os.path.join(temp_dir, 'test_case_1.xml')
            assert not os.path.exists(expected_file)

